# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"find_sentence_in_abstract": "00_utils.ipynb",
         "split_into_sentences": "00_utils.ipynb",
         "alphabets": "00_utils.ipynb",
         "prefixes": "00_utils.ipynb",
         "suffixes": "00_utils.ipynb",
         "starters": "00_utils.ipynb",
         "acronyms": "00_utils.ipynb",
         "websites": "00_utils.ipynb",
         "get_pubmed_records": "00_utils.ipynb",
         "get_attribute_text": "00_utils.ipynb",
         "get_segment": "00_utils.ipynb",
         "sentence_has_phrase": "00_utils.ipynb",
         "replace_outof_vocab_words": "00_utils.ipynb",
         "nlp": "02_text_patterns.ipynb",
         "extra_vocab": "00_utils.ipynb",
         "special_tokens": "00_utils.ipynb",
         "take_while": "02_text_patterns.ipynb",
         "partition": "02_text_patterns.ipynb",
         "partition_all": "02_text_patterns.ipynb",
         "n_grams": "02_text_patterns.ipynb",
         "lemmatize": "02_text_patterns.ipynb"}

modules = ["core.py"]

doc_url = "https://markusstrasser.github.io/octoflow/"

git_url = "https://github.com/markusstrasser/octoflow/tree/master/"

def custom_doc_links(name): return None
