# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://markusstrasser.github.io/octopus-core/"

git_url = "https://github.com/markusstrasser/octopus-core/tree/master/"

def custom_doc_links(name): return None
